languageCode = "en-us"
title = "knabben"
theme = "ananke"
baseURL = "http://thefind.live/"
googleAnalytics = "UA-46699622-2"

[params]
  custom_css = ["css/custom.css"]
  description = "HTP and others BS"
  site_logo = ""
  twitter = "https://twitter.com/ak_ndb"
  github = "https://github.com/knabben/"
  linkedin = "https://www.linkedin.com/in/amim/"
	recent_posts_number = 10
