baseURL = 'https://opssec.in/'
languageCode = 'en-us'
theme = 'hugo-theme-learn'
title = 'Forced Brain'

[params]
themeVariant = "blue"
disableLandingPage = false


[outputs]
home = [ "HTML", "RSS" ]
