baseURL = 'https://opssec.in/'
languageCode = 'en-us'
theme = 'hugo-theme-learn'
title = 'compulsory thinking'

[params]
themeVariant = "blue"
disableLandingPageButton = true


[outputs]
home = [ "HTML", "RSS" ]
